#!/bin/bash
#SBATCH --job-name=targets
#SBATCH -c 2
#SBATCH --mem=20G
#SBATCH --time=48:00:00
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err
#SBATCH --chdir=$HOME/workspaces/DCD.tienhoven_scRNAseq.2024

/packages/easy-build/software/singularity/3.7.0/bin/singularity exec \
    --env OMP_NUM_THREADS=1 \
    --env R_LIBS_SITE=/packages/singularity/shared_cache/rbioc/rlibs/bioc-3.18 \
    -B /packages,/scratch,/run \
    /packages/singularity/shared_cache/rbioc/vscode-rbioc_3.18.sif \
    Rscript -e "targets::tar_make()"

