project:
  type: book

book:
  title: "HPAP scRNAseq Analysis rs3842752"
  author: 
  - name: "Denis O'Meally"
    email: domeally@coh.org
    orcid: 0000-0001-7749-9506
    affiliation: "Department of Diabetes & Cancer Discovery Science, <br/> Arthur Riggs Diabetes & Metabolism Research Institute, City of Hope"
  date: "2024-3-25" 
  chapters:
    - index.qmd
    - part: "Publication figs"
      chapters: 
        - figureX.qmd
        - figureXXsuppl.qmd
    - cell_wish_list.qmd
    - pancdb_metadata.qmd
    - umap_lognorm.qmd
    - beta_cells_umap.qmd
    - part: "DEGs"
      chapters:
      # - beta_cells_DE_muscat.qmd
      - beta_cells_DE_rs3842752.qmd
      - beta_cells_DE_rs3842753.qmd
      - beta_cells_DE_rs689.qmd
      # - DEG_rs3842752_edgeR.qmd
      # - DEG_rs3842753_edgeR.qmd
      # - DEG_rs689_edgeR.qmd
    - part: "Stress score"
      chapters: 
      - ins_expression.qmd
      - boxplots_beta_cells_HK.qmd
    - part: "ER genes"
      chapters:
      - boxplots_beta_cells.qmd
      - boxplots_beta_cells_rs3842753.qmd
      - boxplots_beta_cells_rs689.qmd
      - boxplots_alpha_beta_cells.qmd
      - boxplots_alpha_cells.qmd
      - boxplots_delta_cells.qmd
      #- boxplots_epsilon_cells.qmd
      - boxplots_gamma_cells.qmd
      - boxplots_acinar_cells.qmd
      - boxplots_ductal_cells.qmd
      - boxplots_ductal_MUC5B_cells.qmd
      - boxplots_other_cells.qmd
    - part: "Other"
      chapters:
      - xbp1u_plots.qmd
      - spliced_plots.qmd
    - part: "Marker genes"
      chapters:
      - violin.qmd
    - part: "Cell type proportions"
      chapters:
      - propeller.qmd
      - propeller_endocrine.qmd
  appendices: 
    - QC_PCA.qmd
    - QC_RLE.qmd
    - ins_snps.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto




