
---
title: "Beta cells: DEG rs3842752"
date: "2024-5-21" 
date-modified: last-modified
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE
)
```


```{r }
#| code-fold: true
#| code-summary: "Setup"
suppressPackageStartupMessages({
    library(tidyseurat)
    library(Seurat)
    library(targets)
    library(ggplot2)
    library(ggrepel)
    library(ggdist)
    library(ggsignif)
    library(ggpubr)
    require(showtext)
    font_add_google(name = "Roboto", family = "Roboto")
    font_add_google(name = "Roboto Condensed", family = "Roboto Condensed")
    showtext_auto()

})

tar_config_set(store = "/scratch/domeally/DCD.tienhoven_scRNAseq.2024/_targets")
tar_source("/scratch/domeally/DCD.tienhoven_scRNAseq.2024/R")
cpus <- hprcc::slurm_allocation()$CPUs

tar_load(seurat_object_lognorm_annotated)
seurat_object <- load_seurat(seurat_object_lognorm_annotated)

seurat_object <- seurat_object |>
    dplyr::filter(diabetes_status == "NODM")

make_plots_clickable()
```

## Differential expression

```{r }
bulk <- AggregateExpression(
    seurat_object,
    return.seurat = TRUE,
    assays = "RNA",
    group.by = c("cell_type", "orig.ident", "rs3842752_consensus")
) |>
    separate(.cell, into = c("cell_type", "orig.ident", "rs3842752_consensus"), sep = "_", remove = FALSE)

beta.bulk <- subset(bulk, cell_type == "Beta")
```

::: {.panel-tabset}

## DESeq2

```{r }
Idents(beta.bulk) <- "rs3842752_consensus"

de_markers <- FindMarkers(beta.bulk,
    ident.1 = "GA", # case/numer
    ident.2 = "GG", # control/denom
    test.use = "DESeq2", verbose = F, pseudocount.use = 0.001, min.pct = 0.25
)

de_markers$gene <- rownames(de_markers)

volcano_plot(
    .data = de_markers,
    .transcripts = "gene",
    pvalue = "p_val",
    FDR = "p_val_adj",
    FDR_cutoff = 0.05,
    log2FoldChange = "avg_log2FC",
    log2FoldChange_cutoff = 1,
    title = "Beta cells: rs3842752",
    subtitle = "Upregulated in susceptible (<- GG) protected (GA ->) cells",
)
```

### GSEA

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA for rs3842752 protected (GA) v susceptible (GG) beta cells",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "GO",
    ont = "BP"
)
gsea_results$plot
```

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA for rs3842752 protected (GA) v susceptible (GG) beta cells",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "KEGG"
)
gsea_results$plot
```

## Wilcoxon rank sum test

```{r }
de_markers <- FindMarkers(beta.bulk,
    ident.1 = "GA", ident.2 = "GG", test.use = "wilcox", verbose = FALSE, min.pct = 0.25, pseudocount.use = 0.001
)

de_markers$gene <- rownames(de_markers)

volcano_plot(
    .data = de_markers,
    .transcripts = "gene",
    pvalue = "p_val",
    FDR = "p_val_adj",
    FDR_cutoff = 0.05,
    log2FoldChange = "avg_log2FC",
    log2FoldChange_cutoff = 1,
    title = "Beta cells: rs3842752",
    subtitle = "Upregulated in susceptible (GG <-) v protected (GA ->)",
)
```

### GSEA

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA for rs3842752 protected (GA) v susceptible (GG) beta cells",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "GO",
    ont = "BP"
)
gsea_results$plot
```

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA for rs3842752 protected (GA) v susceptible (GG) beta cells",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "KEGG"
)
gsea_results$plot
```

::::

## Differential expression between Male & Female donors' beta cells

```{r }
bulk <- AggregateExpression(
    seurat_object,
    return.seurat = TRUE,
    assays = "RNA",
    group.by = c("cell_type", "orig.ident", "sample_sex")) |>
    separate(.cell, into = c("cell_type", "orig.ident", "sample_sex"), sep = "_", remove = FALSE)

beta.bulk <- subset(bulk, cell_type == "Beta")

```

::: {.panel-tabset}

## DESeq2

```{r }
Idents(beta.bulk) <- "sample_sex"

de_markers <- FindMarkers(beta.bulk,
    ident.1 = "M", # case
    ident.2 = "F", # control
    test.use = "DESeq2", verbose = F, pseudocount.use = 0.001, min.pct = 0.25
)

de_markers$gene <- rownames(de_markers)

volcano_plot(
    .data = de_markers,
    .transcripts = "gene",
    pvalue = "p_val",
    FDR = "p_val_adj",
    FDR_cutoff = 0.05,
    log2FoldChange = "avg_log2FC",
    log2FoldChange_cutoff = 1,
    title = "Beta-cell Differential Expression",
    subtitle = "Upregulated in female (F <-) vs male (M ->) cells",
)
```

### GSEA

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA Results for Male v Female beta cells",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "GO",
    ont = "BP"
)
gsea_results$plot
```

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA Results for Male v Female beta cells",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "KEGG"
)
gsea_results$plot
```


## Wilcoxon rank sum test

```{r }
de_markers <- FindMarkers(beta.bulk,
    ident.1 = "M",
    ident.2 = "F", test.use = "wilcox", verbose = F, min.pct = 0.25, pseudocount.use = 0.001
)

de_markers$gene <- rownames(de_markers)

volcano_plot(
    .data = de_markers,
    .transcripts = "gene",
    pvalue = "p_val",
    FDR = "p_val_adj",
    FDR_cutoff = 0.05,
    log2FoldChange = "avg_log2FC",
    log2FoldChange_cutoff = 1,
    title = "Beta-cell Differential Expression",
    subtitle = "Upregulated in female (F <-) vs male (M ->) cells",
)
```

### GSEA

```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA Results for Male v Female",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "GO",
    ont = "BP"
)
gsea_results$plot
```


```{r }
gsea_results <- perform_gsea(
    .data = de_markers,
    title = "GSEA Results for Male v Female",
    .transcripts = "gene",
    .log2fc = "avg_log2FC",
    log2fc_threshold = 0,
    analysis_type = "KEGG"
)
gsea_results$plot
```

::::
