#' Annotate human cell types using SinglR
#'
#' Uses the SingleR::SingleR() function to label cell types according to expression profiles 
#' from the databases made available via the the `{celldex}` package. The Seurat object per-cell 
#' metadata is updated with `{ref}_type`, `{ref}_type_fine`, `{ref}_type`, `{ref}_type`, columns. 
#' Cell types are taken from the pruned labels in the `celldex` package.
#' 
#' DICE: 1561 bulk RNA-seq samples of sorted cell populations from the Database of Immune Cell Expression
#' HPCA: 713 microarray samples from the Human Primary Cell Atlas
#' BED: 259 bulk RNA-seq samples generated by Blueprint and ENCODE from pure populations of stroma and immune cells
#' MID: 114 bulk RNA-seq samples of sorted immune cell populations that can be found in GSE107011
#' NHD: 211 bulk human microarray samples of sorted hematopoietic cell populations that can be found in GSE24759
#' See for details https://bioconductor.org/packages/release/data/experiment/html/celldex.html
#'
#' @name seurat_annotate_cell_type
#' @param seurat_object a Seurat object or a path to a seurat object saved as "qs" format
#' @ref reference database, c("DICE", "HPCA", "BED", "MID", "NHD"), Default = "DICE"
#' @return a Seurat object with cell type annotations
#' @source https://bioconductor.org/books/release/SingleRBook/
#' @author Denis O'Meally, Yu-Husan Fu
#' @export
seurat_gpt_cell_type <- function(seurat_object, group.by = "seurat_clusters", tissue = "human pancreas", out_folder = "gpt_cell_type_out") {

    seurat_object <- load_seurat(seurat_object)

    # check the group.by column is in the metadata table
    if (!(group.by %in% colnames(seurat_object[[]]))) {
        stop(glue::glue("The group.by column `{group.by}` is not in the Seurat object metadata."))
    }

    Seurat::DefaultAssay(seurat_object) <- "RNA"
    Seurat::Idents(seurat_object) <- group.by

    all_markers <- Seurat::FindAllMarkers(seurat_object, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
    
    cell_types <- gptcelltype(all_markers, tissuename=tissue, model='gpt-4', topgenenumber = 10)

    seurat_object@meta.data$gpt_cell_type <- cell_types[as.character(Idents(seurat_object))]

    # rename
    cell_type_table <- seurat_object@meta.data |> 
        tibble::rownames_to_column(var = "cell") |>
        dplyr::select(cell, !!!group.by, gpt_cell_type) 
    
    sample_id <- seurat_object[[]]$orig.ident[1]

    cell_type_path <- glue::glue("{analysis_cache}/{out_folder}/{sample_id}.csv")
    dir.create(dirname(cell_type_path), showWarnings = FALSE, recursive = TRUE)

    cell_type_table |> write.csv(cell_type_path, row.names = FALSE, quote = FALSE)

    return(cell_type_path)
}
