
#' Calculate Percent Spliced per Cell for a Specific Gene
#'
#' This function calculates the percentage of spliced RNA for a specific gene in each cell,
#' using spliced and unspliced count matrices generated by STARsolo. It can also perform
#' optional normalization using housekeeping genes.
#'
#' @param path Character string. Path to the SJ/Summary.csv file from STARsolo output.
#'   This path is used to construct paths to other required files.
#' @param gene_name Character string. The name of the gene for which to calculate the splicing ratio.
#' @param housekeeping_genes Character vector. Optional. Names of housekeeping genes to use for normalization.
#'   If NULL (default), no housekeeping normalization is performed.
#'
#' @return Character string. Path to the CSV file containing the calculated ratios and counts.
#'
#' @details
#' The function performs the following steps:
#' 1. Extracts the sample identifier from the input path.
#' 2. Constructs paths to spliced and unspliced matrices, barcodes, and features files from STARsolo output.
#' 3. Loads the spliced and unspliced matrices, barcodes, and features.
#' 4. Identifies the row index for the specified gene.
#' 5. Calculates the ratio of spliced to total RNA for the gene in each cell.
#' 6. Creates a tibble with cell barcodes, calculated ratios, and count information.
#' 7. If housekeeping genes are provided, performs normalization and adds normalized counts.
#' 8. Saves the results to a CSV file.
#'
#' The output CSV includes the following columns for each cell:
#' - cell: Cell barcode
#' - counts_ratio_[gene_name]: Percentage of spliced RNA
#' - spliced_counts_[gene_name]: Raw spliced counts
#' - unspliced_counts_[gene_name]: Raw unspliced counts
#' - total_counts_[gene_name]: Total counts (spliced + unspliced)
#'
#' If housekeeping genes are provided, additional columns are included:
#' - spliced_counts_[gene_name]_hk: Normalized spliced counts
#' - unspliced_counts_[gene_name]_hk: Normalized unspliced counts
#' - total_counts_[gene_name]_hk: Normalized total counts
#'
#' @note This function requires the following packages: dplyr, Matrix, readr, stringr, qs, tibble, and glue.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' path <- "/path/to/STARsolo/output/HPAP-019/Solo.out/SJ/Summary.csv"
#' # Without housekeeping normalization
#' result_path <- percent_spliced_per_cell(path, "INS")
#' # With housekeeping normalization
#' result_path_hk <- percent_spliced_per_cell(path, "INS", housekeeping_genes = c("GAPDH", "ACTB"))
#' result_tibble <- readr::read_csv(result_path_hk)
#' print(result_tibble)
#' }
percent_spliced_per_cell <- function(path, gene_name, housekeeping_genes = NULL) {
    require(dplyr)
    require(Matrix)
    require(readr)
    require(stringr)
    require(qs)
    require(tibble)
    require(glue)

    orig.ident <- stringr::str_extract(path, "HPAP-\\d+")
    message("Start calculating ", gene_name, " ratio per cell for sample ", orig.ident)

    # Correct the paths
    spliced_path <- gsub("SJ/Summary.csv", "Velocyto/filtered/spliced.mtx", path, fixed = TRUE)
    unspliced_path <- gsub("SJ/Summary.csv", "Velocyto/filtered/unspliced.mtx", path, fixed = TRUE)
    barcodes_path <- gsub("SJ/Summary.csv", "Velocyto/filtered/barcodes.tsv", path, fixed = TRUE)
    features_path <- gsub("SJ/Summary.csv", "Velocyto/filtered/features.tsv", path, fixed = TRUE)

    if (!file.exists(spliced_path) || !file.exists(unspliced_path) || !file.exists(barcodes_path) || !file.exists(features_path)) {
        stop("One or more files do not exist. Please check the paths.")
    }

    spliced <- as(Matrix::readMM(spliced_path), "CsparseMatrix")
    unspliced <- as(Matrix::readMM(unspliced_path), "CsparseMatrix")
    barcodes <- readr::read_lines(barcodes_path)
    features <- readr::read_tsv(features_path, col_names = c("gene_id", "gene_name", "type"), show_col_types = FALSE, progress = FALSE)
    message("Loaded spliced and unspliced matrices")

    # Identify the row index for the nominated gene in the features table
    gene_index <- which(features$gene_name == gene_name)
    if (length(gene_index) == 0) {
        stop(gene_name, " not found in the features.")
    }

    # Extract spliced and unspliced counts for the nominated gene
    spliced_counts <- spliced[gene_index, , drop = FALSE]
    unspliced_counts <- unspliced[gene_index, , drop = FALSE]

    # Calculate the ratio (spliced / total)
    total_counts <- spliced_counts + unspliced_counts
    counts_ratio <- (spliced_counts / total_counts) * 100
    message("Calculated ratio for ", gene_name, " per cell")

    ratio_tibble <- tibble(
        cell = barcodes,
        counts_ratio = as.numeric(counts_ratio),
        spliced_counts = as.numeric(spliced_counts),
        unspliced_counts = as.numeric(unspliced_counts),
        total_counts = as.numeric(total_counts)
    ) %>%
        mutate(cell = glue("{orig.ident}_{cell}-1")) %>%
        # Append gene_name to every column name
        rename_with(~ paste0(., "_", gene_name), -cell)

    # Housekeeping gene normalization (if housekeeping_genes is provided)
    if (!is.null(housekeeping_genes)) {
        housekeeping_indices <- which(features$gene_name %in% housekeeping_genes)
        housekeeping_counts <- spliced[housekeeping_indices, ] + unspliced[housekeeping_indices, ]
        sum_housekeeping_counts <- colSums(housekeeping_counts)

        # Normalize gene counts by the sum of housekeeping gene counts
        normalize_counts <- function(counts) {
            normalized <- log1p((counts / sum_housekeeping_counts) * 10000)
            normalized[is.infinite(normalized)] <- 0
            return(as.numeric(normalized))
        }

        # Add normalized counts to the ratio_tibble
        ratio_tibble <- ratio_tibble %>%
            mutate(
                !!paste0("spliced_counts_", gene_name, "_hk") := normalize_counts(spliced_counts),
                !!paste0("unspliced_counts_", gene_name, "_hk") := normalize_counts(unspliced_counts),
                !!paste0("total_counts_", gene_name, "_hk") := normalize_counts(total_counts)
            )
    }

    # Apply filtering after all calculations
    ratio_tibble <- ratio_tibble %>%
        filter(!is.na(!!sym(paste0("counts_ratio_", gene_name))))

    ratio_tibble_path <- glue::glue("{analysis_cache}/percent_spliced_{gene_name}_out/{orig.ident}_{gene_name}_ratio_per_cell.csv")
    dir.create(dirname(ratio_tibble_path), recursive = TRUE, showWarnings = FALSE)

    write.csv(ratio_tibble, ratio_tibble_path, row.names = FALSE, quote = FALSE)
    message("Saved ratio tibble")

    return(ratio_tibble_path)
}
